### ISSUE TITLE
Error: SQLITE_ERROR: no such table: files

### ISSUE THREAD

**Issue by Philomath88** [fjrdomingues/autopilot#109]
node ui -i 
node:internal/process/promises:288
            triggerUncaughtException(err, true /* fromPromise */);
            ^

Error: SQLITE_ERROR: no such table: files
--> in Database#all('\nSELECT path, hash, timestamp \nFROM files\n', [Function (anonymous)])
    at files (/Users/maxmustermann/Projects/autopilot/modules/db.js:114:12)
    at new Promise (<anonymous>)
    at getDBFiles (/Users/maxmustermann/Projects/autopilot/modules/db.js:113:19)
    at codeBaseGapFill (/Users/maxmustermann/Projects/autopilot/modules/codeBase.js:35:25)
    at main (/Users/maxmustermann/Projects/autopilot/ui.js:172:25)
    at Object.<anonymous> (/Users/maxmustermann/Projects/autopilot/ui.js:249:30)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32) {
  errno: 1,
  code: 'SQLITE_ERROR',
  __augmented: true
}

**Comment by hatkyinc2** [comment]
@Philomath88 node ui --reindex=true -t "TASK" should get that fixed

**Comment by hatkyinc2** [comment]
Might need to make the init process more robust and self recovering, currently it's just delete the `.autopilot` directory in your codebase

**Comment by fjrdomingues** [comment]
This happens to me sometimes when I delete the .db file and not the .autopilot folder
