### ISSUE TITLE
No matching files found in the database. Indexing is required.

### ISSUE THREAD

**Issue by Philomath88** [fjrdomingues/autopilot#110]
Do I maybe have to run some kind of initialisation command that I am missing? 

No matching files found in the database. Indexing is required.
/Users/maximiliandoelle/Projects/autopilot/modules/summaries.js:76
    throw new Error("Cannot run without summaries. Indexing is required.");
          ^

Error: Cannot run without summaries. Indexing is required.
    at readAllSummaries (/Users/maximiliandoelle/Projects/autopilot/modules/summaries.js:76:11)
    at async getSummaries (/Users/maximiliandoelle/Projects/autopilot/modules/summaries.js:98:21)
    at async main (/Users/maximiliandoelle/Projects/autopilot/ui.js:205:21)

Node.js v18.16.0

**Comment by hatkyinc2** [comment]
@Philomath88  `node ui --reindex=true -t "TASK"` should get that fixed

**Comment by hatkyinc2** [comment]
GapFill functionality should help with this in the future

**Comment by egoshly** [comment]
I got the same error, and ran the command @hatkyinc2 mentioned above.
Task: Fix bugs in code
No matching files found in the database. Indexing is required.
/Users/jamesmclendon/autopilot/modules/summaries.js:79
    throw new Error("Cannot run without summaries. Indexing is required.");
          ^

Error: Cannot run without summaries. Indexing is required.
    at readAllSummaries (/Users/jamesmclendon/autopilot/modules/summaries.js:79:11)
    at async getSummaries (/Users/jamesmclendon/autopilot/modules/summaries.js:100:21)
    at async main (/Users/jamesmclendon/autopilot/ui.js:59:21)

Node.js v18.16.0
