### ISSUE TITLE
Followed install , installed

### ISSUE THREAD

**Issue by lanalex** [fjrdomingues/autopilot#124]
I installed the package with npm install (and configured .env with the API key and everything) but I get this error: 

(seedoo_v2)  ✘ alexlan@alexsmbp  ~/Code/autopilot   main ±  node ui -t "TEST"
/Users/alexlan/Code/autopilot/node_modules/langchain/prompts.js:1
(function (exports, require, module, __filename, __dirname) { export * from './dist/prompts/index.js'
                                                              ^^^^^^

SyntaxError: Unexpected token export
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:617:28)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/alexlan/Code/autopilot/agents/genericAgent.js:1:90)

**Comment by hatkyinc2** [comment]
That's weird, it's not even real code stuff, just the initial imports.

What's your node version?
```
> node -v
v18.15.0
```

I'm thinking it's either a node version or some config around it

**Comment by hatkyinc2** [comment]
I've also tried
```
# node --version
v19.9.0
```
Which is the latest dockerhub node version

You can try this Dockerfile here
https://github.com/fjrdomingues/autopilot/pull/125/files

```
docker build . --tag autopilot
```
```
docker run --rm -it -v $pwd:/code autopilot -t "TASK"
```
or in windows
```
docker run --rm -it -v ${pwd}:/code autopilot -t "TASK"
```

**Comment by hatkyinc2** [comment]
@lanalex if you are using node version above 18 and still have the issue do let us know
