### ISSUE TITLE
ReferenceError: Headers is not defined

### ISSUE THREAD

**Issue by Brblol** [fjrdomingues/autopilot#145]
playground2021/autopilot$ **node ui -t "when users are inputing their task allow them to set their preferfed model, gpt-3 or gpt-4"**
Checking for gaps between the DB and the codebase and reconciling them.
Gap fill: 33 gaps found, fixing...
File modified: modules/summaries.test.js
Processing file: modules/summaries.test.js
Error processing file: modules/summaries.test.js ReferenceError: **Headers is not defined**
    at createRequest (/home/m/Dropbox/playground2021/autopilot/node_modules/langchain/dist/util/axios-fetch-adapter.cjs:240:21)
    at fetchAdapter (/home/m/Dropbox/playground2021/autopilot/node_modules/langchain/dist/util/axios-fetch-adapter.cjs:171:21)
    at dispatchRequest (/home/m/Dropbox/playground2021/autopilot/node_modules/openai/node_modules/axios/lib/core/dispatchRequest.js:58:10)
    at Axios.request (/home/m/Dropbox/playground2021/autopilot/node_modules/openai/node_modules/axios/lib/core/Axios.js:108:15)
    at Function.wrap [as request] (/home/m/Dropbox/playground2021/autopilot/node_modules/openai/node_modules/axios/lib/helpers/bind.js:9:15)
    at /home/m/Dropbox/playground2021/autopilot/node_modules/openai/dist/common.js:149:22
    at /home/m/Dropbox/playground2021/autopilot/node_modules/openai/dist/api.js:1738:133
File modified: agents/advisor.js
Processing file: agents/advisor.js
Error processing file: agents/advisor.js ReferenceError: **Headers is not defined**
    at createRequest (/home/m/Dropbox/playground2021/autopilot/node_modules/langchain/dist/util/axios-fetch-adapter.cjs:240:21)
    at fetchAdapter (/home/m/Dropbox/playground2021/autopilot/node_modules/langchain/dist/util/axios-fetch-adapter.cjs:171:21)
    at dispatchRequest (/home/m/Dropbox/playground2021/autopilot/node_modules/openai/node_modules/axios/lib/core/dispatchRequest.js:58:10)
    at Axios.request (/home/m/Dropbox/playground2021/autopilot/node_modules/openai/node_modules/axios/lib/core/Axios.js:108:15)
    at Function.wrap [as request] (/home/m/Dropbox/playground2021/autopilot/node_modules/openai/node_modules/axios/lib/helpers/bind.js:9:15)
    at /home/m/Dropbox/playground2021/autopilot/node_modules/openai/dist/common.js:149:22
    at /home/m/Dropbox/playground2021/autopilot/node_modules/openai/dist/api.js:1738:133
File modified: agents/coder.js
Processing file: agents/coder.js
Error processing file: agents/coder.js ReferenceError: **Headers is not defined**
    at createRequest (/home/m/Dropbox/playground2021/autopilot/node_modules/langchain/dist/util/axios-fetch-adapter.cjs:240:21)
    at fetchAdapter (/home/m/Dropbox/playground2021/autopilot/node_modules/langchain/dist/util/axios-fetch-adapter.cjs:171:21)
    at dispatchRequest (/home/m/Dropbox/playground2021/autopilot/node_modules/openai/node_modules/axios/lib/core/dispatchRequest.js:58:10)
    at Axios.request (/home/m/Dropbox/playground2021/autopilot/node_modules/openai/node_modules/axios/lib/core/Axios.js:108:15)
    at Function.wrap [as request] (/home/m/Dropbox/playground2021/autopilot/node_modules/openai/node_modules/axios/lib/helpers/bind.js:9:15)
    at /home/m/Dropbox/playground2021/autopilot/node_modules/openai/dist/common.js:149:22
    at /home/m/Dropbox/playground2021/autopilot/node_modules/openai/dist/api.js:1738:133
File modified: agents/genericAgent.js
Processing file: agents/genericAgent.js
Error processing file: agents/genericAgent.js ReferenceError: Headers is not defined
    at createRequest (/home/m/Dropbox/playground2021/autopilot/node_modules/langchain/dist/util/axios-fetch-adapter.cjs:240:21)
    at fetchAdapter (/home/m/Dropbox/playground2021/autopilot/node_modules/langchain/dist/util/axios-fetch-adapter.cjs:171:21)
    at dispatchRequest (/home/m/Dropbox/playground2021/autopilot/node_modules/openai/node_modules/axios/lib/core/dispatchRequest.js:58:10)
    at Axios.request (/home/m/Dropbox/playground2021/autopilot/node_modules/openai/node_modules/axios/lib/core/Axios.js:108:15)
    at Function.wrap [as request] (/home/m/Dropbox/playground2021/autopilot/node_modules/openai/node_modules/axios/lib/helpers/bind.js:9:15)
    at /home/m/Dropbox/playground2021/autopilot/node_modules/openai/dist/common.js:149:22
    at /home/m/Dropbox/playground2021/autopilot/node_modules/openai/dist/api.js:1738:133
File modified: agents/getFiles.js
Processing file: agents/getFiles.js
Error processing file: agents/getFiles.js ReferenceError: Headers is not defined
    at createRequest (/home/m/Dropbox/playground2021/autopilot/node_modules/langchain/dist/util/axios-fetch-adapter.cjs:240:21)
    at fetchAdapter (/home/m/Dropbox/playground2021/autopilot/node_modules/langchain/dist/util/axios-fetch-adapter.cjs:171:21)
    at dispatchRequest (/home/m/Dropbox/playground2021/autopilot/node_modules/openai/node_modules/axios/lib/core/dispatchRequest.js:58:10)
    at Axios.request (/home/m/Dropbox/playground2021/autopilot/node_modules/openai/node_modules/axios/lib/core/Axios.js:108:15)
    at Function.wrap [as request] (/home/m/Dropbox/playground2021/autopilot/node_modules/openai/node_modules/axios/lib/helpers/bind.js:9:15)
    at /home/m/Dropbox/playground2021/autopilot/node_modules/openai/dist/common.js:149:22
    at /home/m/Dropbox/playground2021/autopilot/node_modules/openai/dist/api.js:1738:133
File modified: agents/getFiles.test.js
Processing file: agents/getFiles.test.js
Error processing file: agents/getFiles.test.js ReferenceError: Headers is not defined
    at createRequest (/home/m/Dropbox/playground2021/autopilot/node_modules/langchain/dist/util/axios-fetch-adapter.cjs:240:21)
    at fetchAdapter (/home/m/Dropbox/playground2021/autopilot/node_modules/langchain/dist/util/axios-fetch-adapter.cjs:171:21)
    at dispatchRequest (/home/m/Dropbox/playground2021/autopilot/node_modules/openai/node_modules/axios/lib/core/dispatchRequest.js:58:10)
    at Axios.request (/home/m/Dropbox/playground2021/autopilot/node_modules/openai/node_modules/axios/lib/core/Axios.js:108:15)
    at Function.wrap [as request] (/home/m/Dropbox/playground2021/autopilot/node_modules/openai/node_modules/axios/lib/helpers/bind.js:9:15)
    at /home/m/Dropbox/playground2021/autopilot/node_modules/openai/dist/common.js:149:22
    at /home/m/Dropbox/playground2021/autopilot/node_modules/openai/dist/api.js:1738:133
File modified: agents/indexer.js
Processing file: agents/indexer.js
Error processing file: agents/indexer.js ReferenceError: Headers is not defined
    at createRequest (/home/m/Dropbox/playground2021/autopilot/node_modules/langchain/dist/util/axios-fetch-adapter.cjs:240:21)
    at fetchAdapter (/home/m/Dropbox/playground2021/autopilot/node_modules/langchain/dist/util/axios-fetch-adapter.cjs:171:21)
    at dispatchRequest (/home/m/Dropbox/playground2021/autopilot/node_modules/openai/node_modules/axios/lib/core/dispatchRequest.js:58:10)
    at Axios.request (/home/m/Dropbox/playground2021/autopilot/node_modules/openai/node_modules/axios/lib/core/Axios.js:108:15)
    at Function.wrap [as request] (/home/m/Dropbox/playground2021/autopilot/node_modules/openai/node_modules/axios/lib/helpers/bind.js:9:15)
    at /home/m/Dropbox/playground2021/autopilot/node_modules/openai/dist/common.js:149:22
    at /home/m/Dropbox/playground2021/autopilot/node_modules/openai/dist/api.js:1738:133
File modified: agents/reviewer.js
Processing file: agents/reviewer.js
Error processing file: agents/reviewer.js ReferenceError: Headers is not defined
    at createRequest (/home/m/Dropbox/playground2021/autopilot/node_modules/langchain/dist/util/axios-fetch-adapter.cjs:240:21)
    at fetchAdapter (/home/m/Dropbox/playground2021/autopilot/node_modules/langchain/dist/util/axios-fetch-adapter.cjs:171:21)
    at dispatchRequest (/home/m/Dropbox/playground2021/autopilot/node_modules/openai/node_modules/axios/lib/core/dispatchRequest.js:58:10)
    at Axios.request (/home/m/Dropbox/playground2021/autopilot/node_modules/openai/node_modules/axios/lib/core/Axios.js:108:15)
    at Function.wrap [as request] (/home/m/Dropbox/playground2021/autopilot/node_modules/openai/node_modules/axios/lib/helpers/bind.js:9:15)
    at /home/m/Dropbox/playground2021/autopilot/node_modules/openai/dist/common.js:149:22
    at /home/m/Dropbox/playground2021/autopilot/node_modules/openai/dist/api.js:1738:133
File modified: benchmarks/files/ui.js
Processing file: benchmarks/files/ui.js
Error processing file: benchmarks/files/ui.js ReferenceError: Headers is not defined
    at createRequest (/home/m/Dropbox/playground2021/autopilot/node_modules/langchain/dist/util/axios-fetch-adapter.cjs:240:21)
    at fetchAdapter (/home/m/Dropbox/playground2021/autopilot/node_modules/langchain/dist/util/axios-fetch-adapter.cjs:171:21)
    at dispatchRequest (/home/m/Dropbox/playground2021/autopilot/node_modules/openai/node_modules/axios/lib/core/dispatchRequest.js:58:10)
    at Axios.request (/home/m/Dropbox/playground2021/autopilot/node_modules/openai/node_modules/axios/lib/core/Axios.js:108:15)
    at Function.wrap [as request] (/home/m/Dropbox/playground2021/autopilot/node_modules/openai/node_modules/axios/lib/helpers/bind.js:9:15)
    at /home/m/Dropbox/playground2021/autopilot/node_modules/openai/dist/common.js:149:22
    at /home/m/Dropbox/playground2021/autopilot/node_modules/openai/dist/api.js:1738:133
File modified: benchmarks/summary_chunks.js
Processing file: benchmarks/summary_chunks.js
Error processing file: benchmarks/summary_chunks.js ReferenceError: Headers is not defined
    at createRequest (/home/m/Dropbox/playground2021/autopilot/node_modules/langchain/dist/util/axios-fetch-adapter.cjs:240:21)
    at fetchAdapter (/home/m/Dropbox/playground2021/autopilot/node_modules/langchain/dist/util/axios-fetch-adapter.cjs:171:21)
    at dispatchRequest (/home/m/Dropbox/playground2021/autopilot/node_modules/openai/node_modules/axios/lib/core/dispatchRequest.js:58:10)
    at Axios.request (/home/m/Dropbox/playground2021/autopilot/node_modules/openai/node_modules/axios/lib/core/Axios.js:108:15)
    at Function.wrap [as request] (/home/m/Dropbox/playground2021/autopilot/node_modules/openai/node_modules/axios/lib/helpers/bind.js:9:15)
    at /home/m/Dropbox/playground2021/autopilot/node_modules/openai/dist/common.js:149:22
    at /home/m/Dropbox/playground2021/autopilot/node_modules/openai/dist/api.js:1738:133
File modified: benchmarks/yellow_to_red.js
Processing file: benchmarks/yellow_to_red.js
Error processing file: benchmarks/yellow_to_red.js ReferenceError: Headers is not defined
    at createRequest (/home/m/Dropbox/playground2021/autopilot/node_modules/langchain/dist/util/axios-fetch-adapter.cjs:240:21)
    at fetchAdapter (/home/m/Dropbox/playground2021/autopilot/node_modules/langchain/dist/util/axios-fetch-adapter.cjs:171:21)
    at dispatchRequest (/home/m/Dropbox/playground2021/autopilot/node_modules/openai/node_modules/axios/lib/core/dispatchRequest.js:58:10)
    at Axios.request (/home/m/Dropbox/playground2021/autopilot/node_modules/openai/node_modules/axios/lib/core/Axios.js:108:15)
    at Function.wrap [as request] (/home/m/Dropbox/playground2021/autopilot/node_modules/openai/node_modules/axios/lib/helpers/bind.js:9:15)
    at /home/m/Dropbox/playground2021/autopilot/node_modules/openai/dist/common.js:149:22
    at /home/m/Dropbox/playground2021/autopilot/node_modules/openai/dist/api.js:1738:133
File modified: modules/autopilotConfig.js
Processing file: modules/autopilotConfig.js
Error processing file: modules/autopilotConfig.js ReferenceError: Headers is not defined
    at createRequest (/home/m/Dropbox/playground2021/autopilot/node_modules/langchain/dist/util/axios-fetch-adapter.cjs:240:21)
    at fetchAdapter (/home/m/Dropbox/playground2021/autopilot/node_modules/langchain/dist/util/axios-fetch-adapter.cjs:171:21)
    at dispatchRequest (/home/m/Dropbox/playground2021/autopilot/node_modules/openai/node_modules/axios/lib/core/dispatchRequest.js:58:10)
    at Axios.request (/home/m/Dropbox/playground2021/autopilot/node_modules/openai/node_modules/axios/lib/core/Axios.js:108:15)
    at Function.wrap [as request] (/home/m/Dropbox/playground2021/autopilot/node_modules/openai/node_modules/axios/lib/helpers/bind.js:9:15)
    at /home/m/Dropbox/playground2021/autopilot/node_modules/openai/dist/common.js:149:22
    at /home/m/Dropbox/playground2021/autopilot/node_modules/openai/dist/api.js:1738:133
File modified: modules/cliOptions.js
Processing file: modules/cliOptions.js

**Comment by hatkyinc2** [comment]
@Brblol What node version are you running?

**Comment by hatkyinc2** [comment]
Try node 18 or up and let us know if you still have an issue.
