### ISSUE TITLE
Error with  node ui -t "FIX_CODE"

### ISSUE THREAD

**Issue by egoshly** [fjrdomingues/autopilot#166]
No matching files found in the database. Indexing is required.
/Users/jamesmclendon/autopilot/modules/summaries.js:79
    throw new Error("Cannot run without summaries. Indexing is required.");
          ^

Error: Cannot run without summaries. Indexing is required.
    at readAllSummaries (/Users/jamesmclendon/autopilot/modules/summaries.js:79:11)
    at async getSummaries (/Users/jamesmclendon/autopilot/modules/summaries.js:100:21)
    at async main (/Users/jamesmclendon/autopilot/ui.js:59:21)

Node.js v18.16.0

**Comment by egoshly** [comment]
what is the command?
