### ISSUE TITLE
No matching files found in the database. Indexing is required.

### ISSUE THREAD

**Issue by 3geniosmx** [fjrdomingues/autopilot#170]
**Describe the issue**
I run the script and this index all files but when tryin to run a task gime this error can you help me bro 

No matching files found in the database. Indexing is required.
/Users/*****/autopilot/modules/summaries.js:79
    throw new Error("Cannot run without summaries. Indexing is required.");
          ^

Error: Cannot run without summaries. Indexing is required.
    at readAllSummaries (/Users/*****/autopilot/modules/summaries.js:79:11)
    at async getSummaries (/Users/*****/autopilot/modules/summaries.js:100:21)
    at async main (/Users/*****/autopilot/ui.js:60:21)

**Comment by hatkyinc2** [comment]
@3geniosmx @JayBuckley7 Did you guys get this on a fresh install?
There are multiple ways to fix it:
* Delete the ~/.autopilot directory in the code base or the db file inside it
* Use --reindex on running `node ui --reindex -task 'TASK'`

**Comment by hatkyinc2** [comment]
@JayBuckley7 what OS and how did you put the codebase directory?
Is it Windows or *nix?  Did you use a relative path or the full path? 

```
# Path to your code, defaults to itself.
# Even if you are on windows this is POSIX style path.
# For example C:\Users\user\code\project
#    would be C:/Users/user/code/project
CODE_DIR=./
```

**Comment by Zoneflow** [comment]
I had the same issue, but I fixed it by using the right format for CODE_DIR. Make sure to use forward slashes, and make sure to use quotes ( ./ doesn't need quotes but I don't know the technical reason why).

Example: CODE_DIR="C:\src\Flutter Apps\app_folder"
