### ISSUE TITLE
Error processing file. Headers is not defined

### ISSUE THREAD

**Issue by CRortyDG** [fjrdomingues/autopilot#171]
**Describe the issue**
Unable to run a task, after finding and indexing the files to process it fails to process them due to 'Headers is not defined'

Error processing file: includes/file-name.php ReferenceError: Headers is not defined
    at createRequest (/home/bitnami/autopilot-gpt/autopilot/node_modules/langchain/dist/util/axios-fetch-adapter.cjs:240:21)
    at fetchAdapter (/home/bitnami/autopilot-gpt/autopilot/node_modules/langchain/dist/util/axios-fetch-adapter.cjs:171:21)
    at dispatchRequest (/home/bitnami/autopilot-gpt/autopilot/node_modules/openai/node_modules/axios/lib/core/dispatchRequest.js:58:10)
    at Axios.request (/home/bitnami/autopilot-gpt/autopilot/node_modules/openai/node_modules/axios/lib/core/Axios.js:108:15)
    at Function.wrap [as request] (/home/bitnami/autopilot-gpt/autopilot/node_modules/openai/node_modules/axios/lib/helpers/bind.js:9:15)
    at /home/bitnami/autopilot-gpt/autopilot/node_modules/openai/dist/common.js:149:22
    at /home/bitnami/autopilot-gpt/autopilot/node_modules/openai/dist/api.js:1738:133

**Version details**
49d96d43240f71abfa432163e3072fb5160167f0

Node version:
v16.20.0

**Task input**
"add a shortcode that outputs hello <name> and and can take 1 paramter of name"

**Expected behavior**
a function added to perform the output of the shortcode and a line to register the shortcode in wordpress

**Additional context**
This is a WordPress plugin.

**Comment by hatkyinc2** [comment]
@CRortyDG Sorry node 16 is not supported at the moment, please use node 18 or above
I've just added it to the README https://github.com/fjrdomingues/autopilot#prerequisites
I did add it to package.json before which should have triggered a warning on `npm install` https://github.com/fjrdomingues/autopilot/blob/main/package.json#L34
