### ISSUE TITLE
I am getting Indexing is required error

### ISSUE THREAD

**Issue by nite-ssh** [fjrdomingues/autopilot#185]
When checking for gaps between the database (DB) and the codebase and attempting to reconcile them, the following error occurs. The process identified 85 gaps with an estimated cost of $0.2491 for filling them. However, the user chose not to proceed with fixing the gap in summarizing.

**Task input**
What was the task text provided?
whats wrong

**Logs**
What did you get on screen:
No matching files found in the database. Indexing is required.
%PUBLIC%/Projects/autopilot/modules/summaries.js:79
    throw new Error("Cannot run without summaries. Indexing is required.");
          ^

Error: Cannot run without summaries. Indexing is required.
    at readAllSummaries (%PUBLIC%/Projects/autopilot/modules/summaries.js:79:11)
    at async getSummaries (%PUBLIC%/Projects/autopilot/modules/summaries.js:100:21)
    at async main (%PUBLIC%/Projects/autopilot/ui.js:65:21)

**Comment by seval124** [comment]
I am getting the same error on Node 20

**Comment by seval124** [comment]
the problem is likely you code dir, try

Example: CODE_DIR=./

**Comment by fjrdomingues** [comment]
Did this solve the issue @nite-ssh?
